### ISSUE TITLE
Docker image changes between build and deploy steps

### ISSUE THREAD

**Issue by whd** [mozilla-services/edge-validator#7]
My guess is that the test step is leaving some artifacts of some kind in the docker image. Our image verification scripts require that the image be the same between the "build" and "deploy" steps.

**Comment by acmiyaguchi** [comment]
This is weird, because the environment loaded from `cache/docker.tar` is unchanged between build and deploy. [1] By docker image, do you mean the `jobs.(build | depoy).docker.image` values, which are `docker:18.02.0-ce-git` and `docker:18.02.0-ce`? [2] I can make them the same value. 

[1] https://github.com/mozilla-services/edge-validator/blob/master/.circleci/config.yml#L38
[2] https://github.com/mozilla-services/edge-validator/blob/master/.circleci/config.yml#L9-L12

**Comment by whd** [comment]
From what I can tell, circleci 2 splits up the build/test/deploy steps, and version.json writes the first "build" step as its identifier (e.g. 56). The sha256 digest of the image is only output in the "deploy" step (e.g. 58, 57 being the test step). The verification script seems to rely on the sha256 digest being output in the job logs of the build step (it pulls down the image, reads the build identifier from /app/version.json, and then reads circleci's corresponding logs from s3). I'm not sure the best place to address this (it may be a bug in our verification script or the default dockerflow example), so I'll consult cloud ops about it.

**Comment by acmiyaguchi** [comment]
@whd Thanks for the details on the verification script, I'm glad the process is well tested. Let me know if there's any action for me to take. If there does happen to be a bug with the circle 2.0 process here, the changes should probably be reflected in the dockerflow source at [`.circle/config.yml`](https://github.com/mozilla-services/Dockerflow/blob/master/.circleci/config.yml).

**Comment by whd** [comment]
After consulting ops it is indeed an issue with our verification script and I've filed an issue to fix this on the ops infrastructure side.
